apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ez3dzr5jf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ez3dzr5jf-nodejs 
  name: ez3dzr5jf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ez3dzr5jf-nodejs 
